### ISSUE TITLE
Hours without a leading zero don't calculate properly

### ISSUE THREAD

**Issue by aligent-phil** [aligent/pert-with-wings#4]
![image](https://user-images.githubusercontent.com/85087316/221062759-cb33550a-5e18-4a87-aaaa-b931999eee48.png)
![image](https://user-images.githubusercontent.com/85087316/221063030-977cf065-0b17-4cce-917b-38d737fb1dd2.png)
If you enter times in a format like `.5h` it doesn't compare the values properly. 
See attached screenshots for an example 

Also there's a typo in 'Likely' and 'Optimistic' for the Likely < Optimistic error message

**Comment by thilinaaligent** [comment]
covered in https://aligent.atlassian.net/browse/PERT-28

**Comment by thilinaaligent** [comment]
covered in https://aligent.atlassian.net/browse/PERT-28
